# Generated by Django 4.1.5 on 2023-03-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0005_postaus_ingressi_alter_postaus_kuva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postaus',
            options={'verbose_name': 'postaus', 'verbose_name_plural': 'postaukset'},
        ),
    ]
