# Generated by Django 4.1.5 on 2023-03-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0007_postaus_otsikko_lower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postaus',
            name='otsikko_lower',
        ),
    ]
